apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netdevops-app
  namespace: monitoring
  labels:
    release: monitoring 
spec:
  selector:
    matchLabels:
      app: netdevops-app
  namespaceSelector:
    matchNames:
      - app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s 