alertmanager:
  alertmanagerSpec:
    secrets:
      - alertmanager-smtp-secret

  config:
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'corporatecatalyst179@gmail.com'
      smtp_auth_username: 'corporatecatalyst179@gmail.com'
      smtp_auth_password_file: '/etc/alertmanager/secrets/alertmanager-smtp-secret/smtp-password'
      smtp_require_tls: true

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h
      receiver: 'gmail-notifications'

    receivers:
      - name: 'gmail-notifications'
        email_configs:
          - to: 'corporatecatalyst179@gmail.com'
            send_resolved: true

      - name: 'null'