grafana:
  envFromSecret: grafana-smtp-secret

  grafana.ini:
    smtp:
      enabled: true
      host: smtp.gmail.com:587
      user: corporatecatalyst179@gmail.com
      password: ${GF_SMTP_PASSWORD}
      from_address: corporatecatalyst179@gmail.com
      from_name: Grafana Alerts