{
 "title": "Kubernetes infrastructure observability",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Running Pod Per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restart Count ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(\n  (\n    node_filesystem_size_bytes{fstype!=\"tmpfs\"}\n    -\n    node_filesystem_avail_bytes{fstype!=\"tmpfs\"}\n  )\n  /\n  node_filesystem_size_bytes{fstype!=\"tmpfs\"}\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  1 -\n  (\n    node_memory_MemAvailable_bytes\n    /\n    node_memory_MemTotal_bytes\n  )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(\n  rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\n) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}