{
 "title": "PostgreSQL Observability",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Database Size ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"netdevops\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlock ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_deadlocks{datname=\"netdevops\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollbacks/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"netdevops\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"netdevops\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active DB Connections ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"netdevops\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "postgresSQL up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  }
 ]
}