apiVersion: apps/v1
kind: Deployment
metadata:
  name: netdevops-worker
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netdevops-worker
  template:
    metadata:
      labels:
        app: netdevops-worker
    spec:
      containers:
        - name: worker
          image: corporatecatalyst/netdevops-app:latest
          imagePullPolicy: Always

          command:
            - sh
            - -c
            - celery -A app.worker.celery_app worker --loglevel=info

          env:
            - name: PROMETHEUS_MULTIPROC_DIR
              value: /tmp/prometheus-shared

          envFrom:
            - configMapRef:
                name: netdevops-app-config
            - secretRef:
                name: netdevops-app-secret 

          volumeMounts:
            - name: logs
              mountPath: /app/logs
            - name: prometheus-shared
              mountPath: /tmp/prometheus-shared

      volumes:
        - name: logs
          emptyDir: {}

        # 🔥 FIX HERE
        - name: prometheus-shared
          persistentVolumeClaim:
            claimName: prometheus-pvc
