apiVersion: v1
kind: ConfigMap
metadata:
  name: netdevops-app-config
  namespace: app

data:
  APP_ENV: "dev"

  # App connection
  DATABASE_URL: "postgresql+psycopg2://netdevops:rotatedpassword123@postgres:5432/netdevops"

  # Redis
  REDIS_URL: "redis://redis:6379/0"

  # Postgres config
  DATABASE_NAME: "netdevops"
  DATABASE_USER: "netdevops"
  DATABASE_PASSWORD: "rotatedpassword123"