apiVersion: v1
kind: Secret
metadata:
  name: netdevops-app-secret
  namespace: app 
type: Opaque
stringData:
  DATABASE_USER: "netdevops"
  DATABASE_PASSWORD: "rotatedpassword123"
  SECRET_KEY: "change-this-later"
