apiVersion: v1
kind: Service
metadata:
  name: netdevops-app
  namespace: app
  labels:
    app: netdevops-app
spec:
  selector:
    app: netdevops-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP